### ISSUE TITLE
Cultivator Design > Change table HTML to fieldsets (menus)

### ISSUE THREAD

**Issue by CodeKittey** [Artificial-Engineering/lycheeJS#100]
changing all those *** table-Elements for layouting to fieldsets

**Comment by martensms** [comment]
This will only be accepted as a valid solution if every single tool depending on the cultivator/design stylesheet works with the new layout - and it is portable to the lychee.ui Stack later.

**Comment by Deathwing121** [comment]
well, it will be a valid solution

**Comment by cookiengineer** [comment]
With the 2016-Q1 Release the plan is to use the `lychee.ui` Stack directly. So this can be closed, as the Editor will also be using the `lychee.ui` Stack.
