### ISSUE TITLE
Museo sans microtypography is not handled perfectionistically.

### ISSUE THREAD

**Issue by DanielDanielDanielDanielDaniel** [Artificial-Engineering/lycheeJS#101]
please fix it.

**Comment by martensms** [comment]
please elaborate or suggest fix.

**Comment by DanielDanielDanielDanielDaniel** [comment]
ok we will leave it, then.

**Comment by martensms** [comment]
Until we have no instructions on what is wrong, we can't fix this issue. Somebody might chime in and translate designer language into coder language, because I can't understand it.
