### ISSUE TITLE
app.Main > Config attachment as JSON

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheeJS#103]
Modifying the boilerplates sucks hard. We don't want to modify the identifier of the `app.Main.settings.client` manually anymore. We need a meta JSON file for that.

We DONT want to have it inside the lychee.pkg (library file), so we need a proper app.Main attachment.

The reason here is that a library can have multiple build targets, each for different platforms, each for different build toolchains. So the app.Main's attachment is the way to go to add descriptions, versions and other meta information for each `build target`.

```json
{
    "identifier": "boilerplate",
    "settings" : {
        "client": "/api/Server?identifier=boilerplate"
    }
}
```

**Comment by martensms** [comment]
Advantage is also that we then can simulate Network Graph problems in future. The fertilizer can build a sandboxed environment with a custom websocket server to isolate networking problems **AND BOTH** DHT problems and NAT trace / balancing problems.

**Comment by martensms** [comment]
Sorbet's sorbet.mod.Server shall automatically overwrite / inject the app.Main's JSON Config, so that you can both have a defaulted standalone setting and a directly integrated one using sorbet's /api/Server?identifier=stuff queries without users having to change anything in the code.

**Comment by cookiengineer** [comment]
This gets more and more important, because the `harvester.js` currently does *NOT* start an `app.Main` instance.

We need a proper profile for all environments that allows the `stash`, `storage` etc. being run on all instances, dependent on their configurations.

As of @dc1c65819433e7e48f1f1310ae841bd7a862f8b3 this is now a blocking issue for proper synchronization across all peer-types.


Suggestion for the new `source/Main.json` sections are `gui` or `cli` (or better names) as a base profile because all environments are dynamically setup at runtime anyways.

Maybe it makes also sense to reuse the proper lycheejs wordings here (`console`, `embedded`, `mobile`, `server` and `desktop`)

**Comment by cookiengineer** [comment]
As of @e0864f674b791c47b6109df05aba3e6d7efe39d6 all Applications are now truly isomorphic. The profiles for each application is set by the `lychee.pkg` `/build/environments/*identifier*/profile` property and optionally overwritten via `lychee.pkginit`.

As all projects are now up and running in a true isomorphic manner, this is solved. The `lychee.pkg` file allows a much more flexible editing API and has an even better integration with the Cultivator Tools.
