### ISSUE TITLE
Find matching name for Fuzz-Tester-Tool

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheeJS#105]
:bug: :ant: :herb: :leaves: :herb: :ant: :bug:

Suggestions so far:

- Deflector (a tool that protects your plant from bugs)
- Insecticidor (a tool that kills all the bugs)
- Strainer (a tool that catches bugs and filters out existing ones)
- Creeper (a plant that fits around your plant and tests its structure)
- Trellis (a tool that helps your plant grow better and faster)

:bug: :ant: :herb: :leaves: :herb: :ant: :bug:

**Comment by Deathwing121** [comment]
The canadian suggests "stake" like the stick a plant can grow up around it.
And maybe Staker can added to discussion. But on the other hand its not that specific like Strainer.
I really like strainer and deflector

**Comment by martensms** [comment]
I tend to agree with Straner more than with the other ideas I had in mind. Those are mostly too hard to either spell (Insecticidor, which in theory would be the perfect match) or too generic to be associated with bugs and bug prevention / testing.

**Comment by Deathwing121** [comment]
so, we stay on Strainer?

**Comment by cookiengineer** [comment]
Jep, I think so, too. What's the tendency of @passiweinberger on this?

**Comment by passiweinberger** [comment]
Insecticidor (a tool that kills all the bugs)

**Comment by cookiengineer** [comment]
Hum, I still think this name is a bit too long to say. It definitely fits the topic most but I dunno about the word. Does anybody know a much simpler alternative to Insecticidor with the same meaning?

**Comment by CodeKittey** [comment]
some synonyms:
* DDT (https://en.wikipedia.org/wiki/DDT)
* Paraquat
* Fungicide

Maybe we kann use Insecticidor but in another way... 
like Insedor (just shorten it up)
or in a acronym IKAB - Insecticidor Kill All Bugs
U know what i mean?
