### ISSUE TITLE
Code Guidlines

### ISSUE THREAD

**Issue by CodeKittey** [Artificial-Engineering/lycheeJS#110]
Just a reminder for the CONTRIBUTION.md:
* .editorconfig 

Beginn writing Coding guidlines for Contributors:
* CSS Name Spacing
* JavaScript how to name functions and variables

**Comment by CodeKittey** [comment]
State abklären wann ein Issue wirklich "Done" gesetzt werden kann.
->  approval via tests und build bots

**Comment by cookiengineer** [comment]
Contribution Guide and Codestyle Guide are ready now and contain all features that are important.
