### ISSUE TITLE
Commit Emojis

### ISSUE THREAD

**Issue by CodeKittey** [Artificial-Engineering/lycheeJS#117]
Find standard commit Emojis
http://www.emoji-cheat-sheet.com/

**Comment by cookiengineer** [comment]
- :trollface: for API-level refactors
- :snowflake: for unstable prototypes

**Comment by cookiengineer** [comment]
I want a robot face for automation!

Related issue is https://github.com/twitter/twemoji/issues/99

**Comment by CodeKittey** [comment]
:monkey_face: for automated things
for performance stuff:
* :light_rail:
* :airplane:
* :oncoming_police_car:
* :rabbit2:
* :tiger2:

maybe for prototype:
* :hatching_chick:

**Comment by cookiengineer** [comment]
I like the :police_car: !

**Comment by CodeKittey** [comment]
okay too long so just this for performance:
:leopard:

**Comment by cookiengineer** [comment]
Performance shall be :turtle:
