### ISSUE TITLE
Suck it, ZenHub

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheeJS#122]
Suck it ZenHub.
You and your shitty nagging popups.

**Comment by cookiengineer** [comment]
We might want to migrate to the [GitHub ScrumBoard extension](https://github.com/Artificial-Engineering/AE-github) that I created. Works for now in Chrome, but is minimalistic and uses Labels to manage the contents. Doesn't reset on Cache clears and uses the chrome.storage API that lasts forever and only requires a personal access token to function.

**Comment by 2075** [comment]
did you try gitlab yet?
