### ISSUE TITLE
osx: symlink forbidden for the average joe into /usr/bin/...

### ISSUE THREAD

**Issue by 2075** [Artificial-Engineering/lycheeJS#131]
another issue is the symlink you are trying to place in /usr/bin/. in osx since 10.11 this is protected by SIP system integrity protection as the system is running rootless, therefore even admin cant sudo there to tweak things.

`ln: /usr/bin/lycheejs-helper: Operation not permitted`

if you keep it like this, the only way to overcome it, would be for the system admin boot into recovery and disable SIP. therefore not the way to go.

i would recommend to put it in general into `/usr/local/bin`

**Comment by cookiengineer** [comment]
Can you verify this is working now? Made sense to put everything in `/usr/local/bin`, so it's the same path on all UNIX systems.

**Comment by 2075** [comment]
error disappeared, this seems to work nao.
