### ISSUE TITLE
lychee.data.MD: Whitespaces inside links leads to unparsed Links

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheejs#133]
The lychee.data.MD decoder currently has a Bug.

The below markdown currently leads to the final reference containing a `[link` inside it, which is not the expected behaviour.

```markdown
This is a [link with whitespaces](http://artificial.engineering)
```

**Comment by cookiengineer** [comment]
The reason why this happens is this split call here: https://github.com/Artificial-Engineering/lycheejs/blob/development/libraries/lychee/source/data/MD.js#L194

Currently, this has a low priority as most links used and understood by the automatically generated API docs only use no whitespaces anyways.

If somebody wants to dig this up and fix the parser, this issue stays opened.

**Comment by dltmd6262** [comment]
Hi! Is this still a valid issue? If you can give me some time to look over the code, I think I can help out :]

**Comment by cookiengineer** [comment]
Hey, jep this is still a valid issue and still open :)

Let me know if you need help digging into this!

**Comment by dltmd6262** [comment]
Thanks! I think changing regex in the string split would be enough, but I'll ask questions if I'm having trouble :]

**Comment by dltmd6262** [comment]
Dang it my mac is not supported.. Is there a way to test a change in the line you mentioned in the comment??

**Comment by cookiengineer** [comment]
What, you had problems installing with the net installer? That net installer works on OSX El Capitan (at least). What OSX version are you using?

The MD parser and HTML parser are in use inside the `/projects/cultivator/api` tool.

**Comment by dltmd6262** [comment]
oops never mind got it working on my macbook :]
I'll sync my fork and make a PR soon!

**Comment by cookiengineer** [comment]
Awesome, looking forward to it <3

**Comment by dltmd6262** [comment]
Would you please review my PR? Thank you :]

**Comment by cookiengineer** [comment]
Yep, merged in. Thank you very much!
