### ISSUE TITLE
Mac OS X Stuff

### ISSUE THREAD

**Issue by AlexUnderMicrocontRoll** [Artificial-Engineering/lycheeJS#145]
Hi Cookieengenier,
habe jetzt die tage versucht das zum laufen zu bringen. Bin zu dem Punkt gekommen wo die ./bin/config.sh fehler frei durchläuft. Da zu habe ich in allen .sh script in dem bin Ordner geändert. einfach den aufruf von `readlink -f` in `greadlink -f` geändert dann hat das Script das Rootverzeichnis richtig gelesen. bis auf den Schritt wo er die chmod ändert hat alles geklappt.
Fixing chmod rights
chmod: -R: No such file or directory
habe schon deswegen geschaut .doch ich glaube ich habe noch iwo ein aufruf von `readlink -f` vergessen.
greadlink ist bei coreutils für OSX dabei.

Momentan läauft der Server doch beim aus führen  diesen `lycheejs-harvester start development;` bekomme ich folgendes zu sehen:

```
  harvester.mod.Fertilizer: FAILURE ("/libraries/breeder | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/breeder | node/dist")  
  harvester.mod.Fertilizer: FAILURE ("/libraries/fertilizer | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/fertilizer | node/dist")  
  harvester.mod.Server: BOOTUP ("/projects/text-chat | null:49156")  
  harvester.mod.Server: BOOTUP ("/projects/over-there | null:49155")  
  harvester.mod.Server: BOOTUP ("/projects/lethalmaze | null:49154")  
  harvester.mod.Server: BOOTUP ("/projects/emoji-chat | null:49153")  
  harvester.mod.Server: BOOTUP ("/projects/boilerplate | null:49152")  
  harvester.mod.Server: FAILURE ("/projects/text-chat | null:49156")  
  /opt/lycheejs-edge/projects/text-chat/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs-edge/projects/text-chat/harvester.js: line 6: harvester.js: command not found
/opt/lycheejs-edge/projects/text-chat/harvester.js: line 7: source/: is a directory
/opt/lycheejs-edge/projects/text-chat/harvester.js: line 9: var: command not found
/opt/lycheejs-edge/projects/text-chat/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs-edge/projects/text-chat/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/lethalmaze | null:49154")  
  /opt/lycheejs-edge/projects/lethalmaze/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs-edge/projects/lethalmaze/harvester.js: line 6: asset: command not found
/opt/lycheejs-edge/projects/lethalmaze/harvester.js: line 7: asset/: is a directory
/opt/lycheejs-edge/projects/lethalmaze/harvester.js: line 9: var: command not found
/opt/lycheejs-edge/projects/lethalmaze/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs-edge/projects/lethalmaze/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/over-there | null:49155")  
  /opt/lycheejs-edge/projects/over-there/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs-edge/projects/over-there/harvester.js: line 6: asset: command not found
/opt/lycheejs-edge/projects/over-there/harvester.js: line 7: asset/: is a directory
/opt/lycheejs-edge/projects/over-there/harvester.js: line 9: var: command not found
/opt/lycheejs-edge/projects/over-there/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs-edge/projects/over-there/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/emoji-chat | null:49153")  
  /opt/lycheejs-edge/projects/emoji-chat/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs-edge/projects/emoji-chat/harvester.js: line 6: asset: command not found
/opt/lycheejs-edge/projects/emoji-chat/harvester.js: line 7: asset/: is a directory
/opt/lycheejs-edge/projects/emoji-chat/harvester.js: line 9: var: command not found
/opt/lycheejs-edge/projects/emoji-chat/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs-edge/projects/emoji-chat/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/boilerplate | null:49152")  
  /opt/lycheejs-edge/projects/boilerplate/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs-edge/projects/boilerplate/harvester.js: line 6: harvester.js: command not found
/opt/lycheejs-edge/projects/boilerplate/harvester.js: line 7: source/: is a directory
/opt/lycheejs-edge/projects/boilerplate/harvester.js: line 9: var: command not found
/opt/lycheejs-edge/projects/boilerplate/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs-edge/projects/boilerplate/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/harvester | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/harvester | node/dist")  
  harvester.mod.Fertilizer: FAILURE ("/libraries/harvester | node-sdl/main")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/harvester | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | html/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | html-nwjs/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | html-webview/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | node/dist")  
  harvester.mod.Fertilizer: FAILURE ("/libraries/lychee | node-sdl/dist")  
  harvester.mod.Fertilizer: FAILURE ("/libraries/strainer | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/boilerplate | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/boilerplate | html-webview/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/boilerplate | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/boilerplate | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/emoji-chat | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/emoji-chat | html-webview/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/emoji-chat | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/emoji-chat | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/lethalmaze | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/lethalmaze | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/mode7 | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/mode7 | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/over-there | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/over-there | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/over-there | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/pong | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/pong | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/text-chat | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/text-chat | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/text-chat | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/tictactoe | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/tictactoe | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/cultivator/editor | html/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/cultivator/editor | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/cultivator/ranger | html-nwjs/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/cultivator/ranger | html-webview/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/cultivator/ranger | html/main")
```

ich weis jetzt nicht ob dein editor schon fertig ist oder nicht aber ich kann ihn nicht starten.
und kannst du mir tip geben wie ich Fehler wie 
` harvester.mod.Fertilizer: FAILURE ("/libraries/breeder | node-sdl/dist") `
beheben kann??

**Comment by cookiengineer** [comment]
1. Wie hast du lycheeJS installiert? Mit oder ohne den net installer?
2. Existieren die lycheejs-<tab><tab> tools in der Shell?
3. Existiert /usr/local/bin/lycheejs-helper? Dieser wird verwendet um die harvester.js zu starten. Scheinbar existiert dieser nicht und/oder das notwendige runtime
4. Ist das lycheeJS-runtime repository in /opt/lycheejs/bin/runtime gecloned?
5. Befindet sich lycheeJS in /opt/lycheejs?

**Comment by cookiengineer** [comment]
Notiz: Die Installationsanweisungen fuer alle Paketmanager aus der netinstall.sh sollten mit lycheeJS shipped werden (vllt. via ./bin/install-dependencies.sh!?)

**Comment by AlexUnderMicrocontRoll** [comment]
ich find das bash script install-dependencies.sh niergends. sorry

**Comment by cookiengineer** [comment]
Kannst du bitte schauen dass alles auf dem gleichen Stand ist wie `git checkout development`? Ich habe deine Fixes dort mit reingenommen.

Habe gerade die Installationsroutinen von dem netinstaller in die `bin/configure.sh` uebernommen. Ein `sudo ./bin/configure.sh` sollte alle Abhaengigkeiten mit Brew (praeferiert) bzw. Macports (fallback) installieren.

Dadurch, dass alle buildbots die configure.sh sowieso aufrufen funzt alles in unserer cloud weiterhin ohne notwendige Aenderungen.

> nur die harverster.js zickt noch rum Wenn ich dann auf dem localhost gehe und dort unter lernen auf (...)

Das sollte so korrekt sein, der Editor funzt im Moment noch nicht, da wir ein paar Sachen fuer den Strainer erst glattziehen wollen. Mit dem Release Ende Maerz (Q1) war die Entscheidung getroffen, auch die Cultivatorprojekte komplett mit lychee ohne HTML zu bauen.

Wenn du testen magst ob alles mit den Runtimes funktioniert kannst du das versuchen:

```bash
cd /opt/lycheejs-edge;
sudo ./bin/configure.sh;

# Sollte die Hilfe des helpers anzeigen mit einem "bootstrap.js" am Anfang (Zeichen dass lychee runtime adapter funzt)

lycheejs-helper;


# Sollte nach einem fertilizer Aufruf einen Ordner in ./projects/boilerplate/build erstellen mit allen nwjs native binaries. Auch fuer OSX.

lycheejs-fertilizer html-nwjs/boilerplate /projects/boilerplate;
```

**Comment by AlexUnderMicrocontRoll** [comment]
if [ "$OS" == "darwin" ]; then

	LYCHEEJS_ROOT=$(cd "$(dirname "$(greadlink -f "$0")")/../"; pwd);
	PROJECT_ROOT=$(realpath --relative-to=$LYCHEEJS_ROOT $PWD);


	OS="osx";
	LYCHEEJS_NODE="$LYCHEEJS_ROOT/bin/runtime/node/osx/$ARCH/node";

elif [ "$OS" == "linux" ]; then

	LYCHEEJS_ROOT=$(cd "$(dirname "$(readlink -f "$0")")/../"; pwd);
	PROJECT_ROOT=$(realpath --relative-to=$LYCHEEJS_ROOT $PWD);


	OS="linux";
	LYCHEEJS_NODE="$LYCHEEJS_ROOT/bin/runtime/node/linux/$ARCH/node";

fi;

**Comment by cookiengineer** [comment]
We need further testers that can verify that the current netinstaller (located at lycheejs.org/install.sh) is working on OSX with `homebrew` as a package manager.

**Comment by CraigglesO** [comment]
Hello, I really want to be a part of this project.
https://github.com/CraigglesO/Algorithms-and-Machine-Learning
This is some of my work.
I also have a mac and would be glad to help with testing.

**Comment by cookiengineer** [comment]
Awesome! Do you have either brew or macports installed on your OSX?

We currently have that as a dependency in order to install the greadlink binary and some other necessary stuff like the binutils and coreutils. See here for details [configure.sh#L76](https://github.com/Artificial-Engineering/lycheeJS/blob/development/bin/configure.sh#L76).


Let me know if I can help, anywhere I can!

We currently need to verify the installation process on OSX:

- (Verified) The installer at [https://lychee.js.org](https://lychee.js.org) should clone everything into `/opt/lycheejs`. At /opt/lycheejs/runtime should be the [lycheeJS-runtime repo](https://github.com/Artificial-Engineering/lycheeJS-runtime].
- **Not verified** Each of the lycheejs-* tools needs to be linked in `/usr/local/bin/lycheejs-*` after the netinstaller. So `which lycheejs-harvester` shall return `/usr/local/bin/lycheejs-harvester`. The equivalent for the `lycheejs-helper` is necessary to have all the correct runtimes.
- **Not verified** Executing `lycheejs-helper env:node file.js` should not exit with a `readlink error` and shall execute the file correctly. See Test instructions below.
- **Not verified** Starting the `lycheejs-harvester` should start the project-specific servers correctly and not exit with an error code. The last time I could test on OSX there was an `execFile()` problem that ignored the shebang (first line with `#!/something/interpreter`) on OSX. So the `node` process.version inside each `/projects/boilerplate/harvester.js` might be the global one (which is not what we want). If it's still not fixed, we might need to execute the `lycheejs-helper` directly instead of the `harvester.js file` in the [harvester.mod.Server](https://github.com/Artificial-Engineering/lycheeJS/blob/development/libraries/harvester/source/mod/Server.js#L125).

**How to verify the lycheejs-helper is integrated with the OS correctly**

```bash
cd /home/blub/does/not/matter;

echo "console.log(process.version)" > test.js;
lycheejs-helper env:node test.js;

# Reply should be v5.5.0
# (which is the version of /opt/lycheejs/runtime/node/<platform>/<arch>/node binary)
```

(Optional) A more detailed stacktrace should of the above `lycheejs-helper env:node somefile.js` command should return something like this in the end, so we can verify the local lycheejs node environment is used and not the globally installed one. Note that I included `strace` for Linux and `dtruss` for OSX. strace is not available on OSX, so you have to use their `dtruss` command instead.

```bash
# LINUX ONLY
strace -f -e trace=execve /usr/local/bin/lycheejs-helper env:node test.js

# OSX ONLY (equivalent alternative)
dtruss -f -t execve /usr/local/bin/lycheejs-helper env:node test.js


# The above should output something like this as the last execve entry:
[pid  2795] execve("/opt/lycheejs/bin/runtime/node/linux/x86_64/node", ["/opt/lycheejs/bin/runtime/node/l"..., "test.js"], [/* 51 vars */]) = 0

```

**Comment by AlexUnderMicrocontRoll** [comment]
When it's not to late i would also contribute with testing lycheejs on macosx.

**Comment by CraigglesO** [comment]
https://github.com/CraigglesO/lycheeJS/blob/development/logs/screen.log

I logged my experience. It did not install to /usr/local/bin/ and I used 'ls' in the directory so you could see.

Another issue is you use sudo brew but my system did not like that (. Luckily I already had all those dependencies installed, but if you just do brew instead it will work. (Also, I had to manually link my binitulus, don't know if that will be an issue in the future)

`Configuring lychee.js ...

> Installing Dependencies ...
	sudo -u root brew install binutils coreutils libicns gnu-sed gnu-tar curl git wget --with-default-names
Error: Cowardly refusing to 'sudo brew install'
You can use brew with sudo, but only if the brew executable is owned by root.
However, this is both not recommended and completely unsupported so do so at
your own risk.
> FAIL

Installation command failed, please verify that this is working (don't forget to sudo):
sudo -u root brew install binutils coreutils libicns gnu-sed gnu-tar curl git wget --with-default-names`


`connor@Craiggless-MBP:~% which lycheejs-harvester
lycheejs-harvester not found`

**Comment by cookiengineer** [comment]
@CraigglesO I was trying to add a "sudo -u username" command to use a specific user for brew. The problem here is that the user seemed to be "root", so the whoami command behaves differently on OSX. Did you execute the script via sudo or did you enter a su; shell before?

If the installation of the dependencies fails, there's nothing executed afterwards. So the configure script does also not add the symlinks into /usr/local/bin/*.

Can you please try out what happens when you execute this script?

```bash
sudo bash -c "logname";
```

On Linux, this outputs the current user and NOT root. If that works on OSX, too - we can use that instead for usage with the sudo -u $USER brew statement.

**Comment by cookiengineer** [comment]
I pushed a small fix on the `development` branch that uses the new logname alternative.

So you can try it out via:

```bash
cd /opt/lycheejs;
git pull origin development;
sudo ./bin/configure.sh;
```

Then hopefully everything runs through (like in the gif file in the README.md).

**Comment by CraigglesO** [comment]
`connor@Craiggless-MBP:~% sudo bash -c "logname";
Password:
connor`

I pulled the changes in the repo and sudo ./bin/configure.sh; and got all positives. :)

`which lycheejs-harvester`
`/usr/local/bin/lycheejs-harvester`

my /usr/bin now includes:
 lycheejs-breeder
 lycheejs-editor
 lycheejs-fertilizer
 lycheejs-harvester
 lycheejs-helper
 lycheejs-ranger
 lycheejs-strainer


Playing around:

> connor@Craiggless-MBP:~/Projects/Lychee% vim test.js 
> connor@Craiggless-MBP:~/Projects/Lychee% lycheejs-helper env:node test.js
> hello world
> connor@Craiggless-MBP:~/Projects/Lychee% ls
> test.js


Trying lycheejs-harvester:
> lycheejs-harvester
>   bootstrap.js: Supported methods are console, Buffer  
>   PARAMETERS FAILURE  
>                                                                 
>   lycheeJS 2016-Q1 Harvester  
>                                                                 
>   Usage: lycheejs-harvester [Action] [Profile] [Flag]           
>                                                                 
>                                                                 
>   Available Actions:                                            
>                                                                 
>      start, status, restart, stop                               
>                                                                 
>   Available Profiles:                                           
>                                                                 
>       development                                               
>       lycheejs.org                                              
>       production                                                
>                                                                 
>   Available Flags:                                              
>                                                                 
>      --sandbox        Disables Fertilizer and Strainer Modules  
>                                                                 
>   Examples:                                                     
>                                                                 
>       lycheejs-harvester start development;                     
>       lycheejs-harvester restart development --sandbox;         
>                                                                 
> 


Verifying correct lecheejs-helper installation:

> connor@Craiggless-MBP:~/Projects/Lychee% echo "console.log(process.version)" > test.js;
> connor@Craiggless-MBP:~/Projects/Lychee% ls
> test.js
> connor@Craiggless-MBP:~/Projects/Lychee% lycheejs-helper env:node test.js;
> v5.5.0
> 



```
Lastly, detailed stack-trace:
connor@Craiggless-MBP:~/Projects/Lychee% sudo dtruss -f -t execve /usr/local/bin/lycheejs-helper env:node test.js
Password:
dtrace: failed to execute /usr/local/bin/lycheejs-helper: dtrace cannot control executables signed with restricted entitlements
```


I am not experienced enough to work around this.

**Comment by CraigglesO** [comment]
Playing some more with development:

```
connor@Craiggless-MBP:~/Projects/Lychee% lycheejs-harvester start development;
  bootstrap.js: Supported methods are console, Buffer  
  BOOTUP (65465)  
  
  
  harvester: SANDBOX mode inactive  
  harvester: harvester.mod.Fertilizer enabled  
  harvester: harvester.mod.Strainer enabled  
  
  
  harvester.net.Server: Connected to null:4848  
  harvester.net.Server: Connected to null:8080  
  

  
  Open your web browser and surf to one of the following hosts:  
  
  
  http://localhost:8080  
  http://192.168.0.45:8080  
  

  
  harvester.mod.Fertilizer: FAILURE ("/libraries/breeder | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/breeder | node/dist")  
  harvester.mod.Server: BOOTUP ("/projects/text-chat | null:49155")  
  harvester.mod.Server: BOOTUP ("/projects/over-there | null:49154")  
  harvester.mod.Server: BOOTUP ("/projects/lethalmaze | null:49153")  
  harvester.mod.Server: BOOTUP ("/projects/boilerplate | null:49152")  
  harvester.mod.Server: FAILURE ("/projects/text-chat | null:49155")  
  /opt/lycheejs/projects/text-chat/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs/projects/text-chat/harvester.js: line 6: harvester.js: command not found
/opt/lycheejs/projects/text-chat/harvester.js: line 7: source/: is a directory
/opt/lycheejs/projects/text-chat/harvester.js: line 9: var: command not found
/opt/lycheejs/projects/text-chat/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs/projects/text-chat/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/over-there | null:49154")  
  /opt/lycheejs/projects/over-there/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs/projects/over-there/harvester.js: line 6: asset: command not found
/opt/lycheejs/projects/over-there/harvester.js: line 7: asset/: is a directory
/opt/lycheejs/projects/over-there/harvester.js: line 9: var: command not found
/opt/lycheejs/projects/over-there/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs/projects/over-there/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/boilerplate | null:49152")  
  /opt/lycheejs/projects/boilerplate/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs/projects/boilerplate/harvester.js: line 6: harvester.js: command not found
/opt/lycheejs/projects/boilerplate/harvester.js: line 7: source/: is a directory
/opt/lycheejs/projects/boilerplate/harvester.js: line 9: var: command not found
/opt/lycheejs/projects/boilerplate/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs/projects/boilerplate/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Server: FAILURE ("/projects/lethalmaze | null:49153")  
  /opt/lycheejs/projects/lethalmaze/harvester.js: line 5: /Applications: is a directory
/opt/lycheejs/projects/lethalmaze/harvester.js: line 6: asset: command not found
/opt/lycheejs/projects/lethalmaze/harvester.js: line 7: asset/: is a directory
/opt/lycheejs/projects/lethalmaze/harvester.js: line 9: var: command not found
/opt/lycheejs/projects/lethalmaze/harvester.js: line 10: syntax error near unexpected token `('
/opt/lycheejs/projects/lethalmaze/harvester.js: line 10: `var _port = parseInt(process.argv[3], 10);'  
  harvester.mod.Fertilizer: FAILURE ("/libraries/fertilizer | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/fertilizer | node/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/harvester | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/harvester | node/dist")  
  harvester.mod.Fertilizer: FAILURE ("/libraries/harvester | node-sdl/main")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/harvester | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | html/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | html-nwjs/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | html-webview/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/lychee | node/dist")  
  harvester.mod.Fertilizer: FAILURE ("/libraries/lychee | node-sdl/dist")  
  harvester.mod.Fertilizer: SUCCESS ("/libraries/strainer | node/main")  
  harvester.mod.Fertilizer: SUCCESS ("/projects/boilerplate | html-nwjs/main")  
```

**Comment by cookiengineer** [comment]
```bash
  /opt/lycheejs/projects/text-chat/harvester.js: line 5: /Applications: is a directory
```

Just as I thought, OSX seems to ignore shebangs in the file. So we need to start the lycheejs-helper directly in the execFile() call. That helped very much!

Gonna fix this tomorrow and ping back here once the fixes are pushed :)

Again, thank you very much!

**Comment by cookiengineer** [comment]
If you start this, it should now also work on OSX:

```bash
cd /opt/lycheejs;

git pull origin development;

lycheejs-harvester start development --sandbox;
```

It should output successfully spawned servers like this:

```bash
  harvester.mod.Server: BOOTUP ("/projects/text-chat | null:49155")  
  harvester.mod.Server: BOOTUP ("/projects/over-there | null:49154")  
  harvester.mod.Server: BOOTUP ("/projects/lethalmaze | null:49153")  
  harvester.mod.Server: BOOTUP ("/projects/boilerplate | null:49152") 
```

Note that the trailing `--sandbox` flag boots up much faster because the initial fertilizer run is skipped. That means if you change something in the core libraries in future, remember to use `sudo ./bin/configure.sh` for recompilation. So the sandboxed mode is way better on slower devices like Raspberry Pis.

**Comment by cookiengineer** [comment]
@CraigglesO Any updates on this? Did it work with the aforementioned pull/start steps?

**Comment by cookiengineer** [comment]
*push*

**Comment by CraigglesO** [comment]
@cookiengineer Hey, I'm sorry. I have played around a little but nothing serious yet. 2 months back I was working in Cambodia and I picked up a nasty virus. I'm taking a lot of meds now and I'll be MIA till next week as they are really strong. Do you think we can talk via a chat system sometime so I can better understand your end goal and how I can contribute?

Craig.

**Comment by cookiengineer** [comment]
Yeah, sure. We're using telegram over here - do you have it, too?
