### ISSUE TITLE
Welcome.js error

### ISSUE THREAD

**Issue by AlexUnderMicrocontRoll** [Artificial-Engineering/lycheejs#156]
Letzte für heute versprochen :).
Die Welcome.js zickt rum.: deswegen glaube ich:

`var _BLOB  = attachments["json"].buffer;`
sieht so aus als ob die attachments undefined sind.

![image](https://cloud.githubusercontent.com/assets/9912964/16859433/18966eea-4a2f-11e6-8ec7-d1c04546373a.png)

`gn8

**Comment by cookiengineer** [comment]
Das bedeutet, dass die Welcome.js noch keine Welcome.json als Anhang hat.

**Comment by cookiengineer** [comment]
Neue Warnung ist drin, sieht dann so aus:

![screenshot](http://i.imgur.com/4A6AnVW.png)
