### ISSUE TITLE
immer noch tutorial

### ISSUE THREAD

**Issue by AlexUnderMicrocontRoll** [Artificial-Engineering/lycheejs#157]
Hi. Ich hänge immer noch am ersten Tutorial.
Alles startet ganz normal. Alles grün. Wenn ich den Browser öffne Sehe ich auch keine Fehler. Doch dann wenn ich versuche eine Chatnachricht zu schicken ( dazu mache ich ein 2. Tab im Browser auf) so wie es im Tutorial steht. Knallt es mit diesen Fehlern.
In der Browser Console bekomme den Fehler:

`WebSocket connection to 'ws://localhost:49156/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

Und im Terminal habe ich diesen:

`(E) harvester.mod.Server: FAILURE ("/projects/tutorial | null:49156")  
  (E) harvester.mod.Server: Report from /opt/lycheejs/libraries/lychee/source/net/remote/Chat.js#L171:  
  (E)                       "TypeError: Cannot read property 'bind' of null" `

**Comment by AlexUnderMicrocontRoll** [comment]
Meine Chat.js aus dem remote Folder:

`lychee.define('app.net.remote.Chat').includes([
    'lychee.net.remote.Chat'
]).exports(function (lychee, app, global, attachments) {

    /*
     * IMPLEMENTATION
     */

    var Class = function (remote) {

        lychee.net.remote.Chat.call(this, 'chat', remote, {
            limit: 1337 // 1337 users allowed to join
        });

    };


    Class.prototype = {


    };


    return Class;

});`

**Comment by AlexUnderMicrocontRoll** [comment]
Meine Chat.js aus dem client Folder:

```javascript

lychee.define('app.net.client.Chat').includes([
	'lychee.net.client.Chat'
]).exports(function(lychee, app, global, attachments) {

	/*
	 * IMPLEMENTATION
	 */

	var Class = function(client) {

		lychee.net.client.Chat.call(this, 'chat', client, {
			room: 'hello-world',
			user: '@awesome'
		});

		this.bind('broadcast', function(data) {
			console.log('BROADCASTED MESSAGE', data);
		}, this);

	};


	Class.prototype = {

		/*
		 * CUSTOM API
		 */

		hello: function(message) {
			console.log("message= "+message);

			message = typeof message === 'string' ? message : null;


			if (message !== null) {

				this.broadcast({
					message: message
				});

			}

		}

	};


	return Class;

});


```

**Comment by AlexUnderMicrocontRoll** [comment]
Und bei nur einem offenen Tab und dem aufruf in der chrome console bekomme ich das

![image](https://cloud.githubusercontent.com/assets/9912964/16873310/aef11c6a-4a92-11e6-92fa-74b7f0b5c32a.png)

**Comment by cookiengineer** [comment]
zum lycheejs-harvester Terminal, [Ctrl] + [C] und neu starten, dann sollte der Fehler nicht mehr auftauchen. Der Client kann nicht zum Server connecten (welcher durch die project/harvester.js gestartet wird)

**Comment by AlexUnderMicrocontRoll** [comment]
Nope bringt nichts.
P.S: Wo sind die Docs überhaupt?

**Comment by cookiengineer** [comment]
Meh, ich glaube ich muss fuer sowas nen reporting tool bauen, damit man das leichter nachvollziehen kann was passiert ist. Docs sind noch nicht ready, ich hab heute angefangen den lychee.js Guide zu schreiben - werden also heute Abend ein paar commits in dem repo https://github.com/Artificial-Engineering/lycheejs-guide landen.

Plan ist, auch die Architektur und alles Techie maessige zu erklaeren, da die Tutorials fuer sowas nicht ausreichen werden.

**Comment by AlexUnderMicrocontRoll** [comment]
Ok ich mach mal pause warte auf das Guide.  Hast mich ganz schön angefixt mit deinen lycheeJS. XD. Auf das AI zeug bin auch gespannt.

**Comment by cookiengineer** [comment]
Alle Inhalte aus den alten Tutorials sind jetzt im lychee.js Guide aufgeschrieben. Es gibt nen follow-up Issue (#159), dieser hier wird geschlossen da Duplicate.
