### ISSUE TITLE
editor 'open' is not opening the project

### ISSUE THREAD

**Issue by ksjogo** [Artificial-Engineering/lycheejs#167]
The click is registered as shown in the console output as
````
(L) SELECTED /projects/pong
core.js:4380 (L) SELECTED open
```
but no further reaction is observable.

**Comment by cookiengineer** [comment]
The Editor is currently work-in-progress, at least until Q4.

Sorry for that, I'm trying to get all the AI stuff stable before the Editor can make better suggestions :)

**Comment by ksjogo** [comment]
No problem, already got a nice editor on my system. :)
