### ISSUE TITLE
visible example of ai'ed code

### ISSUE THREAD

**Issue by ksjogo** [Artificial-Engineering/lycheejs#168]
Is there any practical/visible example of code run through the ai accessible? Would be interesting to see @humansneednotapply in action. :)

**Comment by cookiengineer** [comment]
Yes, that needs to be done after #165 and #91 - still in progress, but I keep this issue open to track docs in the lychee.js Guide.

**Comment by cookiengineer** [comment]
Personal notes for the upcoming website / lychee polish:

AI related demos (for website and upstream project):

- [ ] `pong-bnn` as example
- [ ] `pong-neat` as example
- [ ] `pong-bneat` as example
- [ ] `flappy-enn` as example
