### ISSUE TITLE
Website Polishing (Examples and Guide)

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheejs#174]
The website of lychee.js needs polishing.

Examples: People seem to not find examples or are not happy with the downloads and need github code etc. This seems to be presented in a way that it is not polished enough for people to understand. Make a carousel, endless scroller for examples and more screenshots and screencast (gifs) with a Download button (that can select multiple download options), a github button etc.

Guide: People seem to not find the guide on the website. It is presented in a way that people do not understand, so it must be added to the sidebar buttons AND in a bigger font on the welcome webpage.

**Comment by soundyogi** [comment]
I really like the https://baconjs.github.io/ site.

1. what is it
2. how to get started
3. example

lycheeJS is a really big project and complexity scares people.
So I ask myself, how could lychee be presented in very simple examples.
So one does not feel so overwhelmed.

Since lychee can be used to write games/heavy networked apps aswell as for AI purposes perhaps it is a good Idea to spilt tutorials.

1. For Gamedevs/Appdevs
2. AI Research/ Networking

**Comment by soundyogi** [comment]
Another Idea, (maybe Impossible) is to try and split some parts of the engine and make them consumable by third party apps.
This would ease the vendor "lock-in"

Meteor has similar acceptance issues for example.

**Comment by cookiengineer** [comment]
I had the idea to make a tutorial on how to integrate third-party libraries, so that people can see that they can still use nodejs modules or, say, jquery if they want to. It's completely possible and actually very easy. In the jquery case, you can simply do `const _jquery = lychee.import('$')` and you got jquery in your implementation.

**Comment by cookiengineer** [comment]
The lycheejs-library needs examples in an `./examples` folder, so that is self-sufficient and agnostic without the engine. If people do not want to read the lycheejs-guide, they can just copy/paste the examples into their own codebase.

**Comment by cookiengineer** [comment]
Required: Paper / Demo that learns how the `lychee.ai.strategy` namespace works and how the Code gets automated by the ES/HyperNEAT implementation.

AI Demo: Let an AI play lethalmaze game and figure itself out how to play.

**Comment by cookiengineer** [comment]
The `lychee.ui.Blueprint` priorization through an AI needs a tutorial, so that people can understand that the UI graph is already fully automated in the Boilerplate.

**Comment by cookiengineer** [comment]
New website (raw first iteration) is online. It's totally reduced, no marketing blabla, only the essentials and reduced to the max. It also links now to the lychee.js Guide everywhere, so the guide should now be more easy to find.

No menu, endless scroller, due to easier usage.

However, I think it is still important to explain the typical Workflow in the lychee.js Engine. So I'll try to port the old workflow overview into the `./workflow.html` (standalone) file of the new website.

**Comment by cookiengineer** [comment]
New Examples overview is now ready in `./examples.html`.

Tasks to complete to finish this issue:

- [ ] Automatically build examples with `lycheejs-website/bin/build.sh`
- [ ] Automatically upload them to a new release in the lycheejs-website repo
- [ ] Automatically replace `20XX-XX` string inside the `examples.html` of the website.

**Comment by cookiengineer** [comment]
The new website with live-demos are implemented and automatically published now.
