### ISSUE TITLE
feature/neat: NEAT 2.0 refactor

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheejs#189]
The NEAT refactor has many dependencies to allow a cleaner architecture of the core stack and to allow a simulation-based approach that uses specifications in order to decide the amount of success (fitness of a NEAT agent).

**0. Refactor Phase**:

It is important for all changed features to have proper sandbox support, which means that the `lychee.Environment` algorithmetic for sandboxes (and nested globals) support all new properties and values accordingly.

- [x] `lychee.js Harvester` mods have to keep track of the `/review` folder.
- [x] `lychee.Package` has to be independent of environment-specific algorithmetic.
- [x] `lychee.Environment` has to be independent of platform-specific APIs.
- [x] `lychee.Environment` has to be independent of `lychee.Definition` algorithmetic.
- [x] `lychee.FILENAME` will replace the `lychee.Environment.__FILENAME` property
- [x] `lychee.FEATURES[platform]` will replace the `lychee.Environment` feature detection algorithmetic.
- [x] Modify the `configure.sh` file to include `features.js` and `bootstrap.js` for each platform, so that all features for all platforms are known by default on all platforms.

**1. Simulation Implementation**

The new layer on top of an environment is a `lychee.Simulation` instance which knows the relations of definitions, integration tests and their performance results. It also abstracts the newly implemented `/review` folder per-project and per-library.

- [x] `lychee.Simulation` composite
- [x] `specifications` property that has a syntax similar to `lychee.define()` -> `lychee.specify()`
- [x] `lychee.Specification` that abstracts away `id` and `url` per-specification.
- [x] `validate()` or `evaluate()` method that allows to run all specifications.

**Comment by cookiengineer** [comment]
The new refactored core was included in the 2017-Q4 release and as of now (8h in simulations) it is still stable. The next step is to implement the missing reviews and a validate() or evaluate() method on the Simulation's `_Sandbox` itself.

**Comment by reddysridhar53** [comment]
@cookiengineer I want to contribute and finding difficulty to run development in my local machine. Can you please help me setting it in my local machine?

**Comment by cookiengineer** [comment]
@reddysridhar53 It might be easier to lay something like this out in a chat. Do you have telegram? I have the same account name there.

**Comment by cookiengineer** [comment]
The `lychee.Simulation` is now ready for the evaluation part. The evaluation itself will have to be realized using statistical metrics for each specification, for each test that is defined on the sandbox.

- [ ] Implement `lychee.Simulation.prototype.init()` so that it offers metrics in its sandbox
- [ ] Modify the `_export_loop` so that it will try to evaluate as much as possible, respecting the statistical metrics.
- [ ] Evaluate the idea to reuse the `lychee.ai.neat` Stack on the `lychee.Simulation` itself. If it is not possible (likely outcome) then there should be something like a high-level `lychee.ai.Simulation` that will have the identical API; while trying to use neural networks to modify the code based on the statistical metrics.
