### ISSUE TITLE
Installer doesn't work on Ubuntu 16.0.4. A few bugfixes

### ISSUE THREAD

**Issue by BernardJiang** [Artificial-Engineering/lycheejs#198]
When run installation script on Ubuntu 16.0.4, there are some trivial errors that I fixed. 

sudo bash -c "$(curl -fsSL https://lychee.js.org/install.sh)"

1) Remove "npm" from the list for case of Debian/Ubuntu in bin/maintenance/do-install.sh

REQUIRED_LIST="bash binutils binutils-multiarch coreutils fakeroot icnsutils sed zip unzip tar curl git"

npm is installed together with nodejs. "apt-get -y install npm" will trigger a bug on Ubuntu 16 that stops the script. The better fix would be check if npm is installed. If not, request it separately before continue.

2) Remove option "--retry-connrefused" in bin/maintenance/do-update.sh
curl --location --retry 8 --progress-bar $download_url > $LYCHEEJS_ROOT/bin/runtime.zip;

The default version of curl in Ubuntu 16 is 7.47.0, It doesn't recognize the option "--retry-connrefused".

**Comment by cookiengineer** [comment]
Thanks much for the hints!

> npm is installed together with nodejs. "apt-get -y install npm" will trigger a bug on Ubuntu 16 that stops the script. The better fix would be check if npm is installed. If not, request it separately before continue.

Could you elaborate on that? Does that mean an `apt-get -y install npm` will always trigger a bug and it should be done via `apt-get install npm` normally? Or does it mean I should leave out `npm` as a package because it's bundled with `nodejs` anyways?

pkgs claims that the `npm` package is available separately in universe, but I don't know whether universe is activated by default or not in the LTS versions: https://pkgs.org/download/npm

Regarding the curl flag: meh, gonna find out a clever way to check curl's support for flags; as the `--retry-connrefused` is important for embedded, mobile and Termux installs.

**Comment by cookiengineer** [comment]
Also, as a personal note, this issue is somewhat related to #195 and #193 as it is again npm that causes troubles in automated installations. Prioritization of the `eslint` static bundle should be higher for the Q4 release in December.

**Comment by cookiengineer** [comment]
The curl version detection is :bug: fixed in the `./bin/maintenance/do-update.sh` as of https://github.com/Artificial-Engineering/lycheejs/commit/ca578e9e572ae0c842af5c2174db38fa4e4dd330 and seems to work.

**Comment by BernardJiang** [comment]
Here is the error log when installing npm after nodejs is installed. It seems nobody bothers to fix this npm issue. I suggested that the installation script checks if npm is installed or not. If yes, then don't bother; if no, request the user to install nodejs separately before continuing on install lycheejs. In my own case, I just deleted npm from the list, it worked.



sudo apt-get -y install npm
[sudo] password for bernardkerun: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by BernardJiang** [comment]
A side note for curl version. I downloaded curl-7.61.1.tar.gz and compiled and installed on my Ubuntu 16. It looks fine without any warnings. But when run it, it returns nothing. curl doesn't fetch any data from any website or give any errors. I didn't bother to debug it and went back to default version 7.47.0. It worked without that option.

**Comment by cookiengineer** [comment]
Today I installed and verified the new lychee.js release on an Ubuntu 16.0.4 machine with the outdated curl version. I am currently writing up the documentation for the new [lychee.js Guide](/guides/maintenance), so this issue can be closed now.

Please reopen if problem persists on your machine.
