### ISSUE TITLE
Website examples live demos broken

### ISSUE THREAD

**Issue by msand** [Artificial-Engineering/lycheejs#202]
Seems most of the examples are broken, at least on latest Chrome most resources fail to load. @cookiengineer are you aware of this?

**Comment by cookiengineer** [comment]
Yep, currently the `fertilizer` toolchain wasn't ported to the new Android Oreo SDK yet. This is what I'm currently working on, together with the `node-sdl` platform (this time with a runtime implemented in rust + neon-bindings).

So the demos probably will be up and running again with the next release in December, then it will be possible again to build `html-webview` based bundles again. The last two weeks have rather been busy, but I have planned in to work only on lycheejs again starting the first week of December.

**Comment by cookiengineer** [comment]
Relevant implementations to keep track of:

- [new flow-based implementation](https://github.com/Artificial-Engineering/lycheejs/tree/development/libraries/fertilizer/source/event/flow/html-webview)
- [legacy implementation based on bash](https://github.com/Artificial-Engineering/lycheejs-runtime/tree/master/html-webview)
