### ISSUE TITLE
lycheeJS-website > Tutorials

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheejs#71]
The Tutorials shall have a step-by-step set of tutorials where each tutorial will enhance the application with another sub-featureset of the lycheeJS stack:

Here's the initial list of planned Tutorials. If it has an `x` marker the tutorial is finished and ready:

- [x] Create an App Server
- [x] Create an App Client
- [ ] Create an App UI (requires new Boilerplate from #87 and new Editor structure)
- [ ] Create an App AI (requires AI Demo from #91 and an implemented lychee.ai Stack)
- [ ] Connect an App AI
- [x] Fertilize an App
- [x] Deploy an App

**Comment by CodeKittey** [comment]
We also need a Cheat-Sheet for the lychee Tools

**Comment by cookiengineer** [comment]
Further Tutorial requirement: "Deploy an App" that shows how the typical setup of a `bin/package.sh` file looks like. It might make sense to cross-refer to the `lycheejs-harvester` project in AU.

**Comment by cookiengineer** [comment]
Follow-Up Issue is #159 because documentation is now not hosted on the website anymore and uses the centralized lycheejs-guide repository. So this issue is non-relevant anymore and can be closed.
