### ISSUE TITLE
Editor > Scene State

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheejs#76]
The Editor is currently being messed up as everything is sandboxed at runtime. So it needs a Layouting State that manipulates the Entities initial positions and can be used to layout every Entity and Layer on a grid.

**Comment by martensms** [comment]
Problem: Editor's sandbox in Scene State gets the wrong coordinates of the touch events. They need to be offsetted properly with the canvas' parentNode.scrollTop/scrollLeft offsets in order to work with the scrollbars.
