### ISSUE TITLE
Boilerplate > New Structure with Menu / Blueprint

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheeJS#87]
The boilerplate needs a new structure and the integrated lychee.ui.Menu and lychee.ui.Blueprint workflow.

~~New event flows are reshape, then relayout dependent on Layer-internal dimension updates.~~

**Comment by martensms** [comment]
The Chat project needs a buffer-based implementation for app.ui.Messages, this is required for new Boilerplate Menu integration.

**Comment by cookiengineer** [comment]
The new `lychee.event.Emitter` API allows us to `relay` events to other instances on-the-fly (and even once a time). So the `reshape event` is now being used among the lychee.ui Stack in order to trigger a reflow based on their contents.

This concept works perfectly with the `lychee.ui.Element` now, which is the borderline element into the `lychee.ui.Blueprint` dynamic layouting grid. All the other `lychee.ui` elements have optionally that `reshape event` to re-size and re-order their contents based on their sizes.

There's no bubbling reflow event, so we save a pretty good performance with that concept.

**Comment by cookiengineer** [comment]
As of @8c885804eed499f468aedee4ded456aa80597fb9 all the previous functionality for the Settings Menu have been implemented. Everything is now being splitted up in different `lychee.ui.element.*` elements, each for its own purpose, so that you can freely modify what elements and functionality you want to have in your application.

This resolves this issue here. The layouting engine is tracked in #81
