### ISSUE TITLE
Trash ICON!!

### ISSUE THREAD

**Issue by passiweinberger** [Artificial-Engineering/lycheeJS#94]

**Comment by 2075** [comment]
![trash](https://cloud.githubusercontent.com/assets/1140449/13125693/535da4f8-d5c7-11e5-80b4-3ea27767d24d.jpg)

**Comment by CodeKittey** [comment]
nice one.
this could make it.
At least we need an obvious icon for people like @cookiengineer 
J/K ;)

**Comment by cookiengineer** [comment]
![...](http://i.imgur.com/oKGAF4v.gif)
