### ISSUE TITLE
Breeder > Initial development

### ISSUE THREAD

**Issue by cookiengineer** [Artificial-Engineering/lycheeJS#96]
Evaluate if it makes sense to create helper tools to create a lycheeJS boilerplate for specific purposes:

- lycheeJS integrated project (html / node / ... platform!?)
- lycheeJS as library or HTML5 project (with core.js / main.js)

**Comment by martensms** [comment]
The lycheeJS-breeder Tool is now the tool that automates the initial setup of lycheeJS separated projects.

There are two kinds of projects:
- lycheeJS integrated projects (as before use the lycheeJS ecosystem and build chain with all its advantages).
- lycheeJS separated projects (that have same filesystem structure and use lychee's <platform>/dist builds as a library).


The API of the CLI tool shall be like:


```bash
cd /path/to/Software;

mkdir myproject;
cd myproject;

# This configures and auto-updates the lib/lychee folder with the newest version
# Also creates source, asset, build folders and the lychee.pkg file if not existing
lycheejs-breeder configure html;

# This calls the fertilizer with the path to the current project, so it will be built for that specific platforms setup in the lychee.pkg file.
lycheejs-breeder fertilize;
```

**Comment by martensms** [comment]
In order to work correctly, the breeder and fertilizer.Template requires a package diffing algorithm. It might make sense to port the sorbet.mod.Package algorithm to a generic one that can be reused among other platforms.

Maybe it would fit in a sorbet.data.Package.prototype.sort() or fertilizer.data.Package.prototype.sort(). Still undecided.

**Comment by CodeKittey** [comment]
rename configure command -> setup

**Comment by CodeKittey** [comment]
CRO renamed:
setup -> init
install ->  pull

maybe fertilize can also be renamed to init?!

**Comment by CodeKittey** [comment]
maybe something like
lychee-breeder node add Service
lychee-breeder node add Service chat
would be cool

this will automate the includes and remote.addService in Server.js or Client.js
and will add a new javascript file like chat.js in net/remote with standard Service Template.

**Comment by cookiengineer** [comment]
The Breeder needs now a functionality to automatically create all subfolders in the project convention.


That means it shall create automatically (even if empty):

- /api
- /asset
- /build
- /source

The fertilizer.data.Filesystem requires an mkdir method that should be reused internally, too.
